---
title: "Variations of parameters (p_alpha, tau_max) and running SF, ER models"
subtitle: "SF via sample_pa, ER via gnp"
author: Tuan Pham 
output:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = ".", output_format = "all") })
---

```{r echo=F}
knitr::opts_chunk$set(
  echo = F, eval = T,  
  message=F, warning=F,
  fig.align = "center")
```

```{r include=F}
library(tidyverse)
library(reshape2)
library(purrr)

library(bipartite)
library(igraph)

library(ggpubr)

library(pbmcapply)

source('src/topic_discovery.R')
source('src/topic_analysis.R')

set.seed(3327) # for reproducibility of plotting + cluster assigments 
```


```{r}
data_path <- 'data/params-and-models'
run_params_config <- readRDS(file.path(data_path, 'params.RData'))
data_files <- list.files(path = data_path, pattern = 'data.*\\.RData$') %>% c

param_df <- run_params_config$params
general_params <- run_params_config$general

```


# Analysis 

```{r}
analyze_eachfile <- function(data_file, samp_time = 5) {
  td <- readRDS(file.path(data_path, data_file))
  df_edges <- as_data_frame(td$G)
  time_vec <- seq(from=0,to=td$max_nsteps,by=samp_time)
  topic_distmat <- induced_subgraph(td$G,filter_noderole(V(td$G), 'topics')$name) %>% distances(mode = 'all')
  
  analysis_pertime <- lapply(time_vec, function(t_on) {
    df_edges_selected <- filter(df_edges, onset <= t_on & 
                                  substr(from, start = 1, stop = 1) != substr(to, start = 1, stop = 1))
    
    summarized_by_topics <- select(df_edges_selected, to) %>% group_by(to) %>% summarise(count = length(to)) 
    topic_entropy <- calc_entropy(summarized_by_topics)
    num_topics <- nrow(summarized_by_topics)
    
    summarized_by_agents <- group_by(df_edges_selected, from) %>% summarise(d=mean(topic_distmat[to,to]))
    sub_dist_mean <- mean(summarized_by_agents$d)
    sub_dist_median <- median(summarized_by_agents$d)
    
    return(tibble(t = t_on, topic_entropy, num_topics, sub_dist_mean, sub_dist_median))
  }) %>% bind_rows
  
  return(analysis_pertime)
}

run_analysis_each <- function(comb_ind) {
  data_file <- sprintf('data-%06d.RData', comb_ind)
  anly_df <- analyze_eachfile(data_file)
  return(bind_cols(anly_df, param_df[comb_ind, ]))
}

time_analysis <- pbmclapply(
  param_df$ind, run_analysis_each,
  mc.cores = 6, mc.preschedule	= TRUE) %>% bind_rows()
```


```{r}
analysis_df <- list(time_df = time_analysis)
saveRDS(analysis_df, file.path(data_path, 'analysis.RDS'))
```

# Visualize 


```{r}
analysis_df <- readRDS(file.path(data_path, 'analysis.RDS'))
time_analysis <- analysis_df$time_df

uni_models <- unique(param_df$model_agent)
pa_models <- uni_models[startsWith(uni_models, 'pa')]
gnp_models <- uni_models[startsWith(uni_models, 'gnp')]
```

```{r}
time_analysis
```



```{r warning=F, message=F, fig.width=6, fig.height=5}
select_anly <- time_analysis %>% filter(
  tau_max == 100, 
  model_topic == 'pa_1'
) 

z_err <- 3

c('topic_entropy', 'num_topics', 'sub_dist_median') %>% lapply(function(name_of_Y) {
  df <- select_anly %>%
    mutate(Y = !!sym(name_of_Y)) %>%
    group_by(t, p_alpha) %>%
    summarize(
      mean = mean(Y),
      sd   = sd(Y),
      sem  = sd / sqrt(n()),
      err  = sem, 
      upp  = mean + z_err * err,
      low  = mean - z_err * err
    ) %>%
    ungroup() %>%
    mutate(p_alpha = factor(p_alpha)) 
  df$p_alpha <- factor(df$p_alpha, levels = rev(levels(df$p_alpha)))
  df %>% ggplot(aes(x = t, color = p_alpha, fill = p_alpha)) +
    geom_ribbon(aes(ymin = low, ymax = upp), alpha = 0.1, linetype = 0, show.legend = F) +
    geom_line(aes(y = mean), size=1.1, alpha=0.8) +       
    labs(title = name_of_Y, x = 'iterations (time step)', y = 'mean +/- 3 SEM') +
    scale_color_brewer(palette='Spectral') +
    scale_fill_brewer(palette='Spectral') +
    theme_classic() + 
    theme(
        plot.title = element_text(hjust = 0.5, size = 15),
        text = element_text(size = 12),
        # axis.ticks.length = unit(0, "pt")
    )  
}) -> g_list 


svg("figures/demo/demo-pa.svg", bg = "transparent")
ggarrange(plotlist = g_list, 
          nrow = 3, ncol = 1,
          common.legend = T, 
          align = 'hv', 
          legend = 'right')
dev.off()
```



```{r warning=F, message=F, fig.height = 10, fig.width=8}
z_err <- 2

anly_fields <- c('topic_entropy', 'num_topics', 'sub_dist_median')

select_unimodels <- c("pa_0",  "pa_1", "pa_2",  "pa_3", "pa_4" )
select_unimodels <- c("gnp_0", "gnp_1", "gnp_2")
sapply(select_unimodels, function(mdl_name) {
  select_anly <-
    filter(time_analysis, tau_max == 300, model_topic == mdl_name)
  
  lapply(anly_fields, function(name_of_Y) {
    select_anly %>%
      mutate(Y = !!sym(name_of_Y), p_a = factor(p_alpha)) %>%
      group_by(t, p_a) %>%
      summarize(
        mean = mean(Y),
        sd   = sd(Y),
        sem  = sd / sqrt(n()),
        err  = sem,
        upp  = mean + z_err * err,
        low  = mean - z_err * err
      ) %>%
      ungroup() %>%
      ggplot(aes(
        x = t,
        color = p_a,
        fill = p_a
      )) +
      geom_ribbon(aes(ymin = low, ymax = upp),
                  alpha = 0.3,
                  linetype = 0) +
      labs(title = mdl_name, y = name_of_Y) +
      geom_line(aes(y = mean)) 
  })
}) -> g_list

ggarrange(plotlist = g_list,
          ncol = length(anly_fields), nrow = length(select_unimodels),
          common.legend = T)

```



```{r}
select_taumax <- 200
param_summary <- time_analysis %>% 
  filter(startsWith(model_agent, 'pa')) %>% 
  filter(tau_max == select_taumax) %>%  
  filter(t == max(t)) %>%  
  group_by(p_alpha, model_agent) %>% 
  summarise_at(vars(anly_fields), mean) %>% 
  mutate(agg = (topic_entropy - 8) * log(num_topics - 600) * log(sub_dist_median - 1)) %>% 
  mutate(agg = (agg)) 
  
param_summary

```

```{r fig.width=10}

general_theme <- theme(
  plot.title = element_text(hjust = 0.5, size = 11),
  text = element_text(size = 10),
  axis.text.x = element_text(
    angle = 90,
    hjust = 1,
    vjust = 0.5
  ),
  axis.ticks.y = element_blank(),
  axis.ticks.length = unit(0, "pt"),
  legend.position = 'bottom',
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()
)

c(anly_fields, 'agg') %>% lapply(function(anly_name) {
  ggplot(param_summary, aes(factor(model_agent), factor(p_alpha),)) +
    geom_tile(aes(fill = !!sym(anly_name)), colour = 'white', size = 0) +
    # scale_fill_gradient(low = rgb(0.95,0.95,0.95),high = rgb(0.9,0.3,0.3)) +
    scale_fill_viridis_c() + 
    labs(title = anly_name,
         x = 'model type', 
         y = 'p_alpha') + 
    coord_fixed(ratio=1) +
    general_theme 
}) -> g_list

ggarrange(plotlist = g_list, 
          ncol = 4,
          common.legend = F)
```


