---
title: "Topic/knowledge discovery and diversity in a social network"
subtitle: "A toy model idea"
author: Tuan Pham 
output:
  # revealjs::revealjs_presentation: default
  # ioslides_presentation: default
  # pdf_document:
    # fig_width: 8
    # df_print: tibble
    # includes:
    #   in_header: "preamble.tex"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = ".", output_format = "all") })
---


```{r echo=F}
knitr::opts_chunk$set(
  echo = F, eval = T,  
  message=F, warning=F,
  fig.align = "center")
```

```{r include=F}
library(tidyr)
library(tibble)
library(dplyr)
library(reshape2)
library(purrr)

library(bipartite)
library(igraph)

library(ggplot2)

# library(networkD3)
# library(networkDynamic)

# library(infotheo)

source('utils.R')
set.seed(3327) # for reproducibility of plotting + cluster assigments 
```

```{r}
n_t <- 200
n_a <- 100
tau_max <- 50
tau_0 <- 5
p_alpha <- 0.6
p_beta <- 0.4
p_gamma <- 1 - (p_alpha + p_beta)
setdiff_peropt <- TRUE
max_nsteps <- 50

# n_t <- 15
# n_a <- 6
# tau_max <- 5
# tau_0 <- 1
# p_alpha <- 0.6
# p_beta <- 0.4
# p_gamma <- 1 - (p_alpha + p_beta)
# setdiff_peropt <- TRUE
# max_nsteps <- 20

mdl_gen=list(
  agent = partial(sample_pa,power=1,m=1,directed=F),
  topic = partial(sample_pa,power=1.1,m=1,directed=F))

colors=list(
  agent_vert = rgb(1, 0, 0, 0.8), topic_vert = rgb(0.1, 0.2, 0.9, 0.8),
  agent_edge = rgb(1, 0, 0, 0.6), topic_edge = rgb(0.1, 0.2, 0.9, 0.6),
  init_cross = rgb(0, 0, 0, 0.3), new_cross = rgb(0.3, 0.7, 0.3, 0.8)
)
```


```{r}
C <- matrix(c(1  , 3/4,   0,
              3/4,   0, 3/4,
              0  , 3/4, 3/4), nrow=3)
g <- sample_hierarchical_sbm(100, 10, rho=c(3, 3, 4)/10, C=C, p=1/20)
g
if (require(Matrix)) { image(g[]) }
```





```{r}
P_new <- calc_bipartite_mat(M$TAU,M$A,M$T,p_alpha, p_beta, max_nsteps)
G_new <- update_bipartite_topicagent(G, max_nsteps, p_alpha, p_beta,
                                     tau_max, setdiff_peropt, colors$new_cross)
M_new <- get_separate_matrices(G_new)
```

```{r}
df_edges <- as_data_frame(G_new, 'edges')
```

```{r}

time_vec <- 1:max_nsteps
topic_entropy <- lapply(time_vec, function(t_on) {
  df_edges %>% 
  filter(onset <= t_on & substr(from,start=1,stop=1) != substr(to,start=1,stop=1)) %>% 
  select(to) %>% group_by(to) %>% summarise(count = length(to)) %>% 
  entropy()
}) %>% unlist

tibble(topic_entropy, t=time_vec) %>% ggplot(aes(x=t,y=topic_entropy)) + 
  geom_line() 

```

```{r}

p_alpha_vec <- c(0.1,0.3,0.5,0.7,0.9)
# p_alpha_vec <- c(0.1,0.5,0.9)

calc_entropy <- function(df) {
  total_occ <- sum(df$count)
  
  mutate(df, p = count/total_occ) %>% 
    mutate(p = -p*log(p,base=2)) %>% 
    filter(!is.nan(p)) %>% 
    select(p) %>% sum
}

num_trials <- 1

library(parallel)

cl <- makeCluster(6,  type="FORK")

topic_entropy_dfs <- parLapply(cl, 1:num_trials, function(ind_trial) {
  topic_entropy_df <- lapply(p_alpha_vec, function(p_alpha) {
    
    p_beta <- 1 - p_alpha
    G <- initialize_unipartite(n_a,n_t,tau_0,mdl_gen=mdl_gen)
    G_new <- update_bipartite_topicagent(G, max_nsteps, p_alpha, p_beta,
                                         tau_max, setdiff_peropt, colors$new_cross)
    
    time_vec <- 0:max_nsteps
    topic_entropy <- lapply(time_vec, function(t_on) {
      as_data_frame(G_new) %>%
        filter(onset <= t_on &
                 substr(from, start = 1, stop = 1) != substr(to, start = 1, stop = 1)) %>%
        select(to) %>% group_by(to) %>% summarise(count = length(to)) %>%
        calc_entropy()
    }) %>% unlist
    
    num_topics_agg <- lapply(time_vec, function(t_on) {
      as_data_frame(G_new) %>%
        filter(onset <= t_on &
                 substr(from, start = 1, stop = 1) != substr(to, start = 1, stop = 1)) %>%
        select(to) %>% group_by(to) %>% summarise(count = length(to)) %>%
        nrow
    }) %>% unlist
    
    tibble(topic_entropy, num_topics_agg, t=time_vec, alpha=p_alpha)
  }) %>% bind_rows() %>% 
    mutate(trial=ind_trial)
}) %>% bind_rows

stopCluster(cl)

```



```{r}
topic_entropy_dfs %>% group_by(t,alpha) %>%
  summarise(topic_entropy = mean(topic_entropy)) %>%
  mutate(alpha=as.factor(alpha)) %>% 
  ggplot(aes(x=t,y=topic_entropy, color=alpha)) +
  geom_point() + geom_line()
# 
# topic_entropy_dfs %>% filter(alpha==0.5) %>% 
#   ggplot(aes(x=t,y=topic_entropy, color=as.factor(trial))) + 
#   geom_point() + geom_line()
#   

topic_entropy_dfs %>% group_by(t,alpha) %>%
  summarise(num_topics = mean(num_topics_agg)) %>%
  mutate(alpha=as.factor(alpha)) %>% 
  ggplot(aes(x=t,y=num_topics, color=alpha)) +
  geom_point() + geom_line()
  
```


```{r}
TAU_new_agg <- c(1:20) %>% lapply(function(.) {
  G_new <- update_bipartite_topicagent(G,max_nsteps, p_alpha, p_beta, tau_max, setdiff_peropt)
  M_new <- get_separate_matrices(G_new)
  return(M_new$TAU)
})

TAU_new_agg <- reduce(TAU_new_agg, `+`) / length(TAU_new_agg)
```


```{r}
c("edgelist", "pajek", "ncol", "lgl", "graphml", "gml", "dot", "leda") %>% sapply(function(f) {
      t0 <- Sys.time()
      write_graph(G_new, sprintf('data/test_%s', f), format = f)
      return(Sys.time() - t0)
})

G_import <- read_graph('data/test_gml', format='gml')

all_equal(as_data_frame(G_import, 'vertices') %>% select(-id), 
          as_data_frame(G_new, 'vertices'))
compare(G_new, G_import)
as_data_frame(G_import, 'vertices')

as_data_frame(G_import, 'edges')

as_data_frame(G_import, 'vertices') %>% select(-id)
as_data_frame(G_new, 'vertices')

t0 <- Sys.time()
write_csv(as_data_frame(G_new, 'vertices'), "data/test_nodes.csv")
write_csv(as_data_frame(G_new, 'edges'), "data/test_edges.csv") 
Sys.time() - t0

node_df_import <- read_csv('data/test_nodes.csv')
all_equal(node_df_import, as_data_frame(G_new, 'vertices'))


edge_df_import <- read_csv('data/test_edges.csv')
all_equal(edge_df_import, as_data_frame(G_new, 'edges'))

G_new <- graph_from_data_frame(edge_df_import, vertices = node_df_import, directed = F)

```

```{r}
pseudo_cl <- make_clusters(G_new, membership = V(G_new)$role_id)
layout <- layout_with_kk(G_new, weights=ifelse(crossing(pseudo_cl, G_new),10,1))

# E(G_new)$color[is.na(E(G_new)$color)] <- colors$new_cross

plot(G_new, layout=layout, 
     vertex.label=NA,
     vertex.size=4, vertex.frame.color = rgb(0,0,0,0), 
     edge.curved=0.05, edge.width=0.5)
```

```{r}

```


```{r fig.height=3}
visweb(M$TAU %>% t)
```

```{r warning=F,message=F,fig.height=2.5, fig.width=8}
visweb(log(TAU_new_agg) %>% t, type='none', clear=F)

```

```{r warning=F,message=F,fig.height=2.5, fig.width=8}
visweb(log(P_new) %>% t, type='none', clear=F)
```

```{r fig.height=2.5, fig.width=8}
visweb(M_new$TAU %>% t,  clear=F, type='diagonal')
# visweb(M_new$TAU %>% t, type='none',  clear=F)
```

```{r warning=F,message=F, fig.height=2.5, fig.width=8}

visweb(TAU_new %>% t, type='none', clear=F)
```

```{r fig.width=8,fig.height=3}
aoi_topics <- P_new[,"a1"] %>% sort(decreasing=T)
# plot(log( aoi_topics))

aoi_topics %>% data.frame() %>% rownames_to_column(var='top') %>% 
  rename(p='.') %>% mutate(top=factor(top,levels = top)) %>% 
  ggplot(aes(x=top,y=p)) + 
  geom_bar(stat = "identity") + theme_classic() + 
  theme(axis.text.x = element_text(size=5, angle = 90))
  
```
```{r}
TAU_new <- P_new * 0 
for (i in 1:ncol(P_new)) {
  top_inds <- sort(P_new[,i],decreasing=T,index.return=T)$ix[1:tau_max]
  TAU_new[top_inds,i] <- 1 # P_new[top_inds,i]
}
```

